name: branch_checker             # workflow 名
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #トークンの宣言。必要
  URL: ${{ github.event.pull_request.html_url }} #プルリクのURL。参照していないが、消すと動かない？
jobs:
  build:  # job id
    name:  Check branch # job 名
    runs-on: ubuntu-latest # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）
    steps:
      # - name: Switch to pull request branch
      #   uses: actions/checkout@v3
      #   with:
      #     ref: ${{ github.event.pull_request.head.sha }}
      - name: Check branch 
        run: |
          echo ${{ github.head_ref }}
          if [ "${{ github.head_ref }}" = "dev" ]; then
            exit 1
          fi
