name: pr_checker             # workflow 名
on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ main ]
    paths: 'code/**' #チェックするディレクトリと拡張子の指定
env:
  base_branch: "main"
  diff_path: "code/**"
  target_str: "hoge"
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} #トークンの宣言。必要
  # URL: ${{ github.event.pull_request.html_url }} #プルリクのURL。参照していないが、消すと動かない？
jobs:
  build:  # job id
    name:  Find unauthorized strings # job 名
    runs-on: ubuntu-latest # 仮想環境指定（Windows Server, Ubuntu, Mac OSをサポートする）
    steps:
      - name: Switch to pull request branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      # - name: Fetch base branch
      #   run: git fetch origin ${base_branch}:${base_branch}
      # - name: Run actions using diff_files #変更のあるファイルを抽出する。
      #   run: |
      #     diff_files=`git diff --name-only -G ${target_str} HEAD origin/${base_branch} -- ${diff_path} | tr "\n" " "`
      - name: Display file name if it contains unauthorized strings #差分内に${target_str} を含む場合に、プルリクにコメントし異常終了する。
        run: |
          diff_files=`git diff --name-only -G ${target_str} HEAD origin/${base_branch} -- ${diff_path} | tr "\n" " "`
          if grep ${target_str} ${diff_files}; then
            gh pr comment -b "${diff_files}で${target_str}を検知しました。\n $(grep ${target_str} ${diff_files})" ${{github.event.pull_request.html_url }}
            exit 1
            echo "contains ${target_str}"
          fi
